### ISSUE TITLE
/devices/{deviceAlias}/fwupdate endpoints are mandatory?

### ISSUE THREAD

**Issue by alexkrizsan** [iolinkcommunity/JSON_for_IO-Link#138]
In the version-1-x branch the /devices/{deviceAlias}/fwupdate endpoints (GET, POST) are mandatory. This will require each JSON gateway application to implement the Device FW Update Profile Host side, "FW-Update application". See Figure 20 BLOB Transfer & Firmware Update Profile Sept19.

I suggest making these endpoints optional and extending the GET /gateway/capabilities endpoint with a property regarding this feature, e.g. "deviceFwUpdateSupported".

**Comment by roesekoSICKAG** [comment]
Discussion in WG meeting (23/09/2023):
You are right the endpoint should not be mandatory. The idea of the open api specification is also to use it as a template and remove endpoint not supported by the gateway. 

Anyway it makes also sense to add the property `deviceFwUpdateSupported` and it will be added to the /gateway/capabilities endpoint.

**Comment by alexkrizsan** [comment]
> The idea of the open api specification is also to use it as a template and remove endpoint not supported by the gateway.

Does this apply to any endpoint in the specification? If so, no need to indicate IODD, MQTT, or Device FW Update support. Simply adding error code 103 - "Operation not supported" to each endpoint is sufficient.
On the other hand, allowing the removal of any "base" endpoints can cause integration issues later.

**Comment by roesekoSICKAG** [comment]
In general I would say that it can be applied since there is no process of verification/certification or something similar that verifies that all required endpoints are implemented. Hopefully, this will change at some time ;) 

But it makes also sense to have the availability of "high level" features like IODD, MQTT and Device Update at a certain endpoint that the application can access this and act respectively. The alternative solution would be to test the endpoints which might not be as reliable.
